### PR TITLE
Switch password and konami-id subcommands to integer options

### LINKED ISSUE #270: HTTPError: Response code 400 (Bad Request) in getCard
```
HTTPError: Response code 400 (Bad Request)
    at getCard (/src/card.ts:155:8)
```

Affected commands (at least):
- /art
- /price

Samples (internal):
- https://discord.com/channels/381294999729340417/896778500013449266/1068843573228875826
- https://discord.com/channels/381294999729340417/896778500013449266/1068891504271179887
- https://discord.com/channels/381294999729340417/896778500013449266/1069368255380209674
- https://discord.com/channels/381294999729340417/896778500013449266/1069471172485447680
- https://discord.com/channels/381294999729340417/896778500013449266/1069471881645785138

Reason from API (req-7bgl, req-7bh2): "params/id must be integer"

Root cause: possible incorrect typing on a certain command parameter

### LINKED ISSUE #271: Bad error handling in /art, /price
Errors like #270 are resulting in `DiscordAPIError[40060]: Interaction has already been acknowledged.`

Examples (internal):
- https://discord.com/channels/381294999729340417/896778500013449266/1066372313219616778
- https://discord.com/channels/381294999729340417/896778500013449266/1066812815362506753
- https://discord.com/channels/381294999729340417/896778500013449266/1066813602486558791
- https://discord.com/channels/381294999729340417/896778500013449266/1067974491289960458
- https://discord.com/channels/381294999729340417/896778500013449266/1068843574222925884
- https://discord.com/channels/381294999729340417/896778500013449266/1068891505948901416
- https://discord.com/channels/381294999729340417/896778500013449266/1069471173672443904
- https://discord.com/channels/381294999729340417/896778500013449266/1069471883025731715

### PR DESCRIPTION
**Pull request by kevinlul**
getInputLangStringOption: use buildLocalisedCommand 
Create helpers for name/password/konami-id subcommands
Add getCardSearchOptions for shared logic
Remove simultaneous calls to deferReply and getCard

Closes #270
Closes #271

### CODE REVIEW

**Comment by kevinlul** [comment]
DiscordAPIError[50035]: Invalid Form Body
11.options[0].options[2][APPLICATION_COMMAND_OPTIONS_REQUIRED_INVALID]: Required options must be placed before non-required options

**Comment by kevinlul** [comment]
For /price, `.addStringOption(vendorOption)` comes after the optional inputLangStringOption

File: src/commands/price.ts [hunk 1]
```diff
@@ -58,49 +60,20 @@ export class PriceCommand extends Command {
...
-		);
 		const vendorOption = buildLocalisedCommand(
 			new SlashCommandStringOption().setRequired(true),
 			() => c("command-option").t`vendor`,
 			() => c("command-option-description").t`The vendor to fetch the price data from.`
 		).addChoices(...Object.entries(CHOICES_GLOBAL).map(([value, name]) => buildLocalisedChoice(value, name)));
-		nameSubcommand
-			.addStringOption(nameOption)
-			.addStringOption(vendorOption)
-			.addStringOption(getInputLangStringOption());
```
Comment (kevinlul) [inline src/commands/price.ts:101]: Order got swapped here

**Comment by kevinlul** [comment]
tfw deleted all the choices for input-language

File: src/card.ts [hunk 2]
```diff
@@ -125,10 +125,34 @@ export const Icon = {
 // TODO: remove "kid"
 export type CardLookupType = "name" | "password" | "konami-id" | "kid";
 
+// Determine card search options for commands that use name/password/konami-id subcommands and
+// input-language and result-language options.
+// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
```
Comment (AlphaKretin) [inline src/card.ts:130]: I understand not wanting to waste code on specifying the return of a single-use object but we can (optionally) make it an interface to specify it more cleanly.

File: src/commands/art.ts [hunk 3]
```diff
@@ -80,20 +61,19 @@ export class ArtCommand extends Command {
...
-			end = Date.now();
 			useLocale(resultLanguage);
-			await interaction.editReply({ content: t`Could not find a card matching \`${input}\`!` });
+			const reply = await interaction.reply({
+				content: t`Could not find a card matching \`${input}\`!`,
+				fetchReply: true
+			});
+			return replyLatency(reply, interaction);
 		} else {
+			await interaction.deferReply();
```
Comment (AlphaKretin) [inline src/commands/art.ts:74]: Took me a second to find this, expecting it near the top, but it makes so much more sense to only defer if we know we have a card to fetch. 👍

File: src/commands/search.ts [hunk 4]
```diff
@@ -34,44 +36,15 @@ export class SearchCommand extends Command {
...
-		);
-		const nameOption = buildLocalisedCommand(
-			new SlashCommandStringOption().setRequired(true),
-			() => c("command-option").t`input`,
-			() => c("command-option-description").t`Card name, fuzzy matching supported.`
-		);
-		const passwordSubcommand = buildLocalisedCommand(
-			new SlashCommandSubcommandBuilder(),
-			() => c("command-option").t`password`,
+		).addStringOption(getResultLangStringOption());
```
Comment (AlphaKretin) [inline src/commands/search.ts:41]: Noting for myself that unlike the vendorId in /price, this is optional and can/should come last, so the difference between these two is correct

File: src/commands/search.ts [hunk 5]
```diff
@@ -81,24 +54,17 @@ export class SearchCommand extends Command {
...
 		} else {
 			const embeds = createCardEmbed(card, resultLanguage);
-			end = Date.now();
-			await interaction.editReply({ embeds }); // Actually returns void
+			replyOptions = { embeds };
 		}
-		// When using deferReply, editedTimestamp is null, as if the reply was never edited, so provide a best estimate
-		const latency = end - interaction.createdTimestamp;
-		return latency;
+		const reply = await interaction.reply({ ...replyOptions, fetchReply: true });
```
Comment (AlphaKretin) [inline src/commands/search.ts:67]: Right, we don't defer this one, because all we need to do is get the card.

File: src/locale.ts [hunk 6]
```diff
@@ -139,6 +125,65 @@ export function buildLocalisedChoice<T = string | number>(
...
+	return buildLocalisedCommand(
+		new SlashCommandStringOption().setRequired(false),
+		() => c("command-option").t`input-language`,
+		() => c("command-option-description").t`The language to search in, defaulting to the result language.`
+	).addChoices(...LOCALE_CHOICES);
+}
+
+export function getNameSubcommand(
+	getLocalisedDescription: () => string,
+	requiredStringOption?: SlashCommandStringOption
```
Comment (AlphaKretin) [inline src/locale.ts:138]: Could theoretically extend to support an arbitrary number of extra options, but unlikely to have practical use case. Don't need premature abstraction.

**Review by AlphaKretin — APPROVED** [review]
Have seen you testing and looks good, can test on local if needed

File: src/locale.ts (hunk 6 above)
Comment (kevinlul) [reply src/locale.ts:138]: Yes, I could have made this an array. Because the builder doesn't have a generic addOption method though (only addStringOption, addUserOption, etc.), the generic solution is to accept a lambda that will be passed the builder as an argument.

File: src/commands/search.ts (hunk 5 above)
Comment (kevinlul) [reply src/commands/search.ts:67]: /art and /price are deferred on the success path because we don't have an SLA for the art server or the price API. Search though is basically guaranteed to respond in under 200 ms. The full timeouts we've been seeing are rare, bizarre aberrations to investigate.
